name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_gpu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
#     - name: Install dependencies
#       shell: bash
#       run: |
#         sudo apt-get update
#         sudo apt-get -y install git pip python3-dev
#         sudo pip install cmake scikit-build ninja jinja2 --no-input
#         # Install pytorch 1.11 as required by fbgemm_gpu
#         sudo pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
    - name: check third_party
      run: |
        cd third_paty
        cd fbgemm
        ls
    
    - name: Install TorchRec
      run: sudo python setup.py build develop
      
#     - name: Test Installation
#       run: |
#         pip install torchx-nightly
#         torchx run --scheduler local_cwd test_installation.py:test_installation
#     - name: Test with pytest
#       run: |
#         pip install pytest
#         pytest -s -v -W ignore::pytest.PytestCollectionWarning --continue-on-collection-errors
